version: "3"
services: 
    db:
        image: mongo
        ports:
            - "27017:27017"
    backend: 
        build: ./backend
        ports:
            - "4040:4040"
        depends_on:
            - db
    frontend:
        build: ./frontend
        ports:
            - "8080:8080"
        links: 
            - backend